services:
  - type: web
    name: stremio-subtitrari-noi
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
    healthCheckPath: /manifest.json
    autoDeploy: true